insert into creatures (name, description, image_url, is_custom, user_id) values
('Clownfish', 'Bright orange fish with white stripes that lives among sea anemones. Made famous by finding Nemo.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/242892/medium.jpg', false, null),
('Blue Tang', 'Vivid blue surgeonfish with a yellow tail. Feeds on algae and is an important reef cleaner.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/109563/medium.jpg', false, null),
('Green Sea Turtle', 'Large herbivorous sea turtle found in tropical and subtropical seas worldwide.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6035/medium.jpg', false, null),
('Hawksbill Sea Turtle', 'Critically endangered sea turtle with a narrow pointed beak, used to extract food from crevices.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/13965/medium.jpg', false, null),
('Manta Ray', 'Graceful giant of the ocean with wingspan up to 7 meters. Feeds on plankton by filter feeding.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/19622/medium.jpg', false, null),
('Whale Shark', 'The largest fish in the ocean, reaching 12+ meters. Gentle filter feeder despite its massive size.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/19818/medium.jpg', false, null),
('Nurse Shark', 'Bottom-dwelling shark often found resting motionless on sandy floors. Docile and slow-moving.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/2946/medium.jpg', false, null),
('Reef Shark (Blacktip)', 'Sleek shark easily identified by the black tips on its fins. Common in shallow reef environments.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/4234/medium.jpg', false, null),
('Hammerhead Shark', 'Instantly recognizable by its wide, flat, hammer-shaped head. Usually spotted in schools.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6124/medium.jpg', false, null),
('Moray Eel', 'Serpentine predators with powerful jaws that hide in reef crevices and emerge to ambush prey.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/2897/medium.jpg', false, null),
('Octopus', 'Highly intelligent cephalopod with 8 arms, able to change color and texture in milliseconds.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/3045/medium.jpg', false, null),
('Giant Pacific Octopus', 'The largest octopus species, reaching arm spans of over 4 meters. Lives in cold Pacific waters.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/8231/medium.jpg', false, null),
('Blue-Ringed Octopus', 'Tiny but deadly octopus whose iridescent blue rings flash as a warning before it strikes.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/7892/medium.jpg', false, null),
('Cuttlefish', 'Masters of camouflage that can ripple color patterns across their skin in real time.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/4567/medium.jpg', false, null),
('Nautilus', 'Living fossil with a spiral shell chambered for buoyancy. Swims via jet propulsion.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/12034/medium.jpg', false, null),
('Lionfish', 'Striking red-and-white striped fish with venomous spines. An invasive species in the Atlantic.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/5678/medium.jpg', false, null),
('Stonefish', 'Most venomous fish in the world, camouflaged as a rock on the seafloor.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/9012/medium.jpg', false, null),
('Leafy Sea Dragon', 'Ornate relative of the seahorse with leaf-like appendages for camouflage in kelp.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/11234/medium.jpg', false, null),
('Seahorse', 'Unique fish where the male carries and births the young. Anchors to coral with its tail.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/3456/medium.jpg', false, null),
('Pufferfish', 'Can inflate itself into a spiky ball when threatened. Highly toxic flesh.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6789/medium.jpg', false, null),
('Parrotfish', 'Colorful fish that bites off chunks of coral, digests the algae, and excretes white sand.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/7123/medium.jpg', false, null),
('Humphead Wrasse', 'Massive fish with a distinctive forehead hump. One of the largest reef fish at up to 2 meters.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/8901/medium.jpg', false, null),
('Triggerfish (Clown)', 'Bold yellow, white and black pattern. Known for aggressively defending its nest territory.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/9345/medium.jpg', false, null),
('Barracuda', 'Fast, torpedo-shaped predator with sharp teeth. Often seen cruising reef edges alone.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/4890/medium.jpg', false, null),
('Giant Grouper', 'One of the largest reef fish, capable of swallowing small sharks whole.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/5012/medium.jpg', false, null),
('Stingray', 'Flat-bodied ray that glides along sandy bottoms. Venomous barb used only defensively.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/2345/medium.jpg', false, null),
('Eagle Ray', 'Spotted ray with a long whip tail that flies gracefully through the water column.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/3678/medium.jpg', false, null),
('Electric Ray', 'Can generate up to 220 volts of electricity to stun prey and defend itself.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6234/medium.jpg', false, null),
('Jellyfish (Moon)', 'Translucent, pulsing umbrella-shaped jellyfish with a mild sting. Found worldwide.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/4123/medium.jpg', false, null),
('Lions Mane Jellyfish', 'Largest jellyfish with tentacles up to 37 meters long. Lives in cold northern waters.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/9567/medium.jpg', false, null),
('Box Jellyfish', 'One of the most venomous creatures on Earth. Cube-shaped bell with toxic tentacles.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/8456/medium.jpg', false, null),
('Sea Lion', 'Playful and curious marine mammal that often approaches divers. Expert underwater acrobat.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/2678/medium.jpg', false, null),
('Dolphin', 'Highly intelligent marine mammal that occasionally swims alongside divers.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/1890/medium.jpg', false, null),
('Sperm Whale', 'Deepest-diving whale, capable of descending to 3,000+ meters. Largest brain of any animal.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/7345/medium.jpg', false, null),
('Humpback Whale', 'Famous for its haunting songs and dramatic breaching leaps. Spotted seasonally by divers.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/5890/medium.jpg', false, null),
('Dugong', 'Gentle marine mammal that grazes on seagrass. The real-life inspiration for mermaid legends.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6456/medium.jpg', false, null),
('Nudibranch (Spanish Dancer)', 'Flamboyantly colored sea slug that undulates through the water like a flamenco dancer.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/3901/medium.jpg', false, null),
('Nudibranch (Chromodoris)', 'Jewel-like sea slug in electric blue, white and black. Favorite subject for macro photography.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/4678/medium.jpg', false, null),
('Frogfish', 'Ambush predator that mimics sponges and coral. Among the fastest strikers in the animal kingdom.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/7890/medium.jpg', false, null),
('Mantis Shrimp', 'Punches with the force of a bullet and can see 16 types of color. Vivid and aggressive.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/5123/medium.jpg', false, null),
('Lobster', 'Large crustacean sheltering under ledges. Moves forward slowly but swims backward rapidly.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/2901/medium.jpg', false, null),
('Decorator Crab', 'Camouflages itself by attaching living sponges and anemones to its shell.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/8012/medium.jpg', false, null),
('Porcelain Crab', 'Tiny filter feeder with oversized claws that lives inside sea anemones.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/9234/medium.jpg', false, null),
('Crown of Thorns Starfish', 'Large venomous starfish that preys on coral polyps. Can devastate entire reefs.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6012/medium.jpg', false, null),
('Sea Urchin (Black Longspine)', 'Covered in long sharp spines. Grazes algae and provides shelter for small fish.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/3234/medium.jpg', false, null),
('Sea Cucumber', 'Cylindrical bottom-dweller that processes sediment for nutrients.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/4456/medium.jpg', false, null),
('Feather Star (Crinoid)', 'Ancient relative of starfish with feathery arms that filter food from the current.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/5901/medium.jpg', false, null),
('Basket Star', 'Complex branching brittle star that unfurls its fractal arms at night to catch plankton.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/7012/medium.jpg', false, null),
('Giant Clam', 'Largest bivalve in the world, reaching 1.2 meters and living for over a century.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/8234/medium.jpg', false, null),
('Cone Snail', 'Beautiful spiral shell hiding one of the most potent venoms in the ocean.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/9456/medium.jpg', false, null),
('Flatworm (Polyclad)', 'Paper-thin, brilliantly colored worm that glides over the reef. Often mistaken for nudibranchs.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6678/medium.jpg', false, null),
('Christmas Tree Worm', 'Spiral feathery gills extend from a tube buried in coral. Instantly retracts when approached.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/3890/medium.jpg', false, null),
('Cleaner Shrimp', 'Sets up cleaning stations on the reef where fish line up to have parasites removed.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/5234/medium.jpg', false, null),
('Harlequin Shrimp', 'Striking white shrimp with blue-edged spots that hunts starfish including crown of thorns.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/7456/medium.jpg', false, null),
('Mimic Octopus', 'Impersonates other species including lionfish and flatfish to deter predators.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/8678/medium.jpg', false, null),
('Bioluminescent Plankton', 'Microscopic organisms that glow electric blue when disturbed in the dark.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/9890/medium.jpg', false, null),
('Wobbegong Shark', 'Carpet shark with elaborate skin flaps that make it nearly invisible on the seafloor.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/6890/medium.jpg', false, null),
('Bumphead Parrotfish', 'Massive parrotfish that headbutts coral to scrape off algae. Schools in large groups.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/4012/medium.jpg', false, null),
('Tasseled Wobbegong', 'Ornately fringed ambush predator almost indistinguishable from the reef substrate.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/2123/medium.jpg', false, null),
('Oarfish', 'Longest bony fish in the world, reaching 11 meters. Rarely seen alive by divers.', 'https://inaturalist-open-data.s3.amazonaws.com/photos/1234/medium.jpg', false, null);
