-- Fix creature image URLs — replace placeholder IDs with verified iNaturalist photos

update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/15220643/medium.jpg' where name = 'Clownfish' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/54043219/medium.jpg' where name = 'Blue Tang' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/75876185/medium.jpg' where name = 'Green Sea Turtle' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/30844744/medium.jpg' where name = 'Hawksbill Sea Turtle' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/54971198/medium.jpeg' where name = 'Manta Ray' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/66663643/medium.jpg' where name = 'Whale Shark' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/62174729/medium.jpg' where name = 'Nurse Shark' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/608947383/medium.jpg' where name = 'Reef Shark (Blacktip)' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/2857581/medium.jpg' where name = 'Hammerhead Shark' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/185982166/medium.jpg' where name = 'Moray Eel' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/32158737/medium.jpg' where name = 'Octopus' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/174792488/medium.jpg' where name = 'Giant Pacific Octopus' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/6024676/medium.jpg' where name = 'Blue-Ringed Octopus' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/269553588/medium.jpeg' where name = 'Cuttlefish' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/29425182/medium.jpg' where name = 'Nautilus' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/29001353/medium.jpg' where name = 'Lionfish' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/20210/medium.jpg' where name = 'Stonefish' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/9996656/medium.jpeg' where name = 'Leafy Sea Dragon' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/7679315/medium.jpeg' where name = 'Seahorse' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/51377090/medium.jpg' where name = 'Pufferfish' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/11294069/medium.jpg' where name = 'Parrotfish' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/107582757/medium.jpg' where name = 'Humphead Wrasse' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/79966070/medium.jpg' where name = 'Triggerfish (Clown)' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/64376618/medium.jpeg' where name = 'Barracuda' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/11975452/medium.jpeg' where name = 'Giant Grouper' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/83811529/medium.jpg' where name = 'Stingray' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/31735623/medium.jpg' where name = 'Eagle Ray' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/4969470/medium.jpg' where name = 'Electric Ray' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/128613708/medium.jpg' where name = 'Jellyfish (Moon)' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/112465681/medium.jpeg' where name = 'Lion''s Mane Jellyfish' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/429212562/medium.jpg' where name = 'Box Jellyfish' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/39635759/medium.jpg' where name = 'Sea Lion' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/32417167/medium.jpg' where name = 'Dolphin' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/359394837/medium.jpg' where name = 'Sperm Whale' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/318309104/medium.jpeg' where name = 'Humpback Whale' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/32274342/medium.jpg' where name = 'Dugong' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/229212281/medium.jpg' where name = 'Nudibranch (Spanish Dancer)' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/31057816/medium.jpg' where name = 'Nudibranch (Chromodoris)' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/43767791/medium.jpeg' where name = 'Frogfish' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/30551110/medium.jpeg' where name = 'Mantis Shrimp' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/15586/medium.jpg' where name = 'Lobster' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/134565795/medium.jpg' where name = 'Decorator Crab' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/33369232/medium.jpeg' where name = 'Porcelain Crab' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/460463289/medium.jpg' where name = 'Crown of Thorns Starfish' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/3272392/medium.jpg' where name = 'Sea Urchin (Black Longspine)' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/65472908/medium.jpeg' where name = 'Sea Cucumber' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/57574570/medium.jpeg' where name = 'Feather Star (Crinoid)' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/195547071/medium.jpg' where name = 'Basket Star' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/33350838/medium.jpg' where name = 'Giant Clam' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/179373167/medium.jpg' where name = 'Cone Snail' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/98231002/medium.jpg' where name = 'Flatworm (Polyclad)' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/7828343/medium.jpg' where name = 'Christmas Tree Worm' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/255848236/medium.jpeg' where name = 'Cleaner Shrimp' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/176730093/medium.jpg' where name = 'Harlequin Shrimp' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/6298177/medium.jpg' where name = 'Mimic Octopus' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/233495738/medium.jpg' where name = 'Bioluminescent Plankton' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/29608389/medium.jpg' where name = 'Wobbegong Shark' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/709279/medium.jpg' where name = 'Bumphead Parrotfish' and is_custom = false;
update creatures set image_url = 'https://static.inaturalist.org/photos/63681167/medium.jpg' where name = 'Tasseled Wobbegong' and is_custom = false;
update creatures set image_url = 'https://inaturalist-open-data.s3.amazonaws.com/photos/599309517/medium.jpg' where name = 'Oarfish' and is_custom = false;
